### ISSUE TITLE
Updating User Accounts

### ISSUE THREAD

**Issue by aaron-warren** [CS157A-Team-30/StoreFront_Team30#63]

**Comment by phu-n-tran** [comment]
+ View/Change email
+ View/Change password
+ Display all of the users' information

**Comment by evanugarte** [comment]
Can you display this on its own page? I want to update the navbar in #69 so we can redirect to your work.

**Comment by phu-n-tran** [comment]
You want this right? (I created the file called ProfilePage.js)
![image](https://user-images.githubusercontent.com/43549877/70194829-af5b2100-16b8-11ea-93d6-b113536d3b1d.png)
