### ISSUE TITLE
Add UI for Landing Page When Signed Out

### ISSUE THREAD

**Issue by evanugarte** [CS157A-Team-30/StoreFront_Team30#65]
The page must be added [here](https://github.com/CS157A-Team-30/StoreFront_Team30/blob/3b96d30d8a128ac8282a3048db5c720a2172bf01/storefrontApplication/src/Routing.js#L15)

The page should have big words, a background photo and links to login/sign up
![image](https://user-images.githubusercontent.com/36345325/70100761-a2223180-15e7-11ea-93c0-d25ec2ca8712.png)

**Comment by aaron-warren** [comment]
Works like this by default.
